CREATE TABLE IF NOT EXISTS "location" (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(100) NOT NULL,

    address VARCHAR(255) NOT NULL,
    number INT,
    city VARCHAR(100) NOT NULL,
    state VARCHAR(100),

    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);