CREATE TABLE IF NOT EXISTS "group" (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    creator_id UUID NOT NULL,
    name VARCHAR(100) NOT NULL,

    description TEXT,
    url_img TEXT,

    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY ("creator_id") REFERENCES "user" ("id") ON DELETE CASCADE
);