CREATE TABLE IF NOT EXISTS "consume_log" (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL,
    event_id UUID,

    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    consumed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    FOREIGN KEY ("event_id") REFERENCES "event" ("id") ON DELETE SET NULL,
    FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE
);